version: '2'
services:
    app:
        image: openjdk:8-jdk-alpine
        ports:
            - "8001:8080"
        volumes:
            - .:/app
        working_dir: /app
        command: ./mvnw spring-boot:run
